<a href="https://colab.research.google.com/github/Dipta04/Python-for-ML/blob/main/Module_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
arr = [1,2,3]

print( arr * 5 )

arr = [ x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [36]:
import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


### Ndarray

In [37]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

### Array attributes

In [38]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


### ndarray data type

In [39]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [40]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


### selecting a data type for an array

In [41]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)


arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

### ndarray creation from existing data

In [42]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [43]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [44]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [45]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [46]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [47]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [48]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


### Creating ndarray from scratch

In [49]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [50]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [51]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [52]:
#np.full

arr = np.full((4,3),np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


### array creation with random values

In [53]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.83247768 0.34221793 0.59765898]
 [0.32864617 0.44996921 0.38504814]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [54]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[9 5 8]
 [4 7 3]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [55]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[75.32555448 70.67309052 88.91362268 99.53931839]
  [51.93608838 79.31125242 58.68798467 78.51063902]
  [86.68683378 68.73759166 87.05892028 78.0372678 ]]

 [[62.44057039 60.32881389 55.60245005 78.91299155]
  [94.74970131 57.50457979 78.39333239 85.42813562]
  [71.717856   92.87201994 67.26264679 97.91601538]]

 [[77.92046381 90.82150344 64.49385194 74.08507829]
  [75.62864375 55.60050239 91.63397895 82.54789643]
  [79.68419958 51.77542855 86.77722446 60.75351121]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


### array creation with range functions

In [56]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [57]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [58]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


### creating matrix for Linear algebra

In [59]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [60]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### indexing and slicing

In [61]:
#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [62]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [63]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


### Advanced Indexing

In [64]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [66]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2>1])
arr2[arr2>2] = 0

print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[  2 100   4   5   6]
[[1 2 0]
 [0 0 0]]


In [67]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [68]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
